version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container-name: main-app
    ports:
      - "${DJANGO_PORT}:8000"
    commands: "sh entrypoint.sh"
    env_file:
      - ../prod.env
    depends_on:
      postgres
    volumes:
      - ..:/app/
