name: CI/CD Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH for the VDS
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VDS_SSH_KEY }}

      # Verify the SSH key is loaded
      - name: Verify SSH Key
        run: ssh-add -l

      - name: Debug Remote Directory
        env:
          VDS_USER: ${{ secrets.VDS_USER }}
          VDS_IP: ${{ secrets.VDS_IP }}
          VDS_PROJECT_DIR: ${{ secrets.VDS_PROJECT_DIR }}
        run: |
          ssh -o StrictHostKeyChecking=no $VDS_USER@$VDS_IP << 'EOF'
            echo "Dir: $VDS_PROJECT_DIR"
            cd /home/bot/social_parser && \
            echo "Current Directory: $VDS_PROJECT_DIR"
            ls -al $VDS_PROJECT_DIR
            ls -al $VDS_PROJECT_DIR/.docker/remote_postgres/
          EOF


      # Deploy application to VDS
      - name: Deploy to VDS
        env:
          VDS_USER: ${{ secrets.VDS_USER }}
          VDS_IP: ${{ secrets.VDS_IP }}
          VDS_PROJECT_DIR: ${{ secrets.VDS_PROJECT_DIR }}
        run: |
          ssh -o StrictHostKeyChecking=no $VDS_USER@$VDS_IP << 'EOF'
            cd $VDS_PROJECT_DIR && \
            git pull origin main && \
            docker-compose -f ./.docker/remote_postgres/docker-compose.yml down && \
            docker-compose -f ./.docker/remote_postgres/docker-compose.yml up -d --build
          EOF
